twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        presentation: '@App\TwigServices\PresentationsExtension'
        website: '@App\TwigServices\WebsitesExtension'

when@test:
    twig:
        strict_variables: true
